<?php
/** @package Biblioteca::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("BloqueioMap.php");

/**
 * BloqueioDAO provides object-oriented access to the bloqueio table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Biblioteca::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class BloqueioDAO extends Phreezable
{
	/** @var int */
	public $Idbloqueio;

	/** @var int */
	public $Idlivro;

	/** @var string */
	public $Tipobloqueio;

	/** @var int */
	public $Idmovimentacao;


	/**
	 * Returns the foreign object based on the value of Idlivro
	 * @return Livro
	 */
	public function GetIdlivroLivro()
	{
		return $this->_phreezer->GetManyToOne($this, "fkBloqueioLivro");
	}

	/**
	 * Returns the foreign object based on the value of Idmovimentacao
	 * @return Movimentacao
	 */
	public function GetIdmovimentacaoMovimentacao()
	{
		return $this->_phreezer->GetManyToOne($this, "fkBloqueioMovimentacao");
	}


}
?>