<?php
/** @package Biblioteca::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("LivroMap.php");

/**
 * LivroDAO provides object-oriented access to the livro table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Biblioteca::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class LivroDAO extends Phreezable
{
	/** @var int */
	public $Idlivro;

	/** @var year */
	public $Anoaquisicao;

	/** @var int */
	public $Retiravel;

	/** @var string */
	public $Situacao;

	/** @var string */
	public $Idisbn;

	/** @var int */
	public $Idlocalizacao;


	/**
	 * Returns a dataset of Bloqueio objects with matching Idlivro
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdlivroBloqueios($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fkBloqueioLivro", $criteria);
	}

	/**
	 * Returns a dataset of Movimentacao objects with matching Idlivro
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdlivroMovimentacaos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fkDevolucaoLivro", $criteria);
	}

	/**
	 * Returns a dataset of Reserva objects with matching Dlivro
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetDlivroReservas($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fkReservaLivro", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Idisbn
	 * @return Categorialivro
	 */
	public function GetIdisbnCategorialivro()
	{
		return $this->_phreezer->GetManyToOne($this, "fkLivroCategoria");
	}

	/**
	 * Returns the foreign object based on the value of Idlocalizacao
	 * @return Localizacao
	 */
	public function GetIdlocalizacaoLocalizacao()
	{
		return $this->_phreezer->GetManyToOne($this, "fkLivroLocalizacao");
	}


}
?>