<?php
/** @package Biblioteca::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("LocalizacaoMap.php");

/**
 * LocalizacaoDAO provides object-oriented access to the localizacao table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Biblioteca::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class LocalizacaoDAO extends Phreezable
{
	/** @var int */
	public $Idlocalizacao;

	/** @var int */
	public $Prateleiraposicao;

	/** @var int */
	public $Prateleiranumero;


	/**
	 * Returns a dataset of Livro objects with matching Idlocalizacao
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdlocalizacaoLivros($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fkLivroLocalizacao", $criteria);
	}


}
?>